## NumPy: Practice Problem 3


In [1]:
import numpy as np

### 1. Find dot product of two arrays.
#### a = [2j, 3j],
#### b = [2j, 3j]
#### Level: Easy

In [2]:
np.dot([2j, 3j], [2j, 3j])

(-13+0j)

### 2. Create two arrays of 2-D and find dot product of it.
#### Level: Easy

In [6]:
a = np.random.randint(1,10,(3,2))
b = np.random.randint(11,20,(2,3))
print("a :",a,"\nb :",b)

a : [[6 8]
 [6 1]
 [6 8]] 
b : [[14 13 19]
 [18 13 12]]


In [7]:
np.dot(a,b)

array([[228, 182, 210],
       [102,  91, 126],
       [228, 182, 210]])

### 3. Find vector product of given array.
#### a = np.array([1+2j,3+4j])
#### b = np.array([5+6j,7+8j])
#### Level: Easy

In [8]:
a = np.array([1+2j , 3+4j])
b = np.array([5+6j , 7+8j])
print("a :",a,"\nb :",b)

a : [1.+2.j 3.+4.j] 
b : [5.+6.j 7.+8.j]


In [10]:
np.cross(a,b)

array(0.-16.j)

### 4. FIrst create given array withound using direct value insted use numpy utlities and then find inner product for given array.
#### a = [[ 0 1 2 3] [ 4 5 6 7] [ 8 9 10 11]]
#### b = [[12 13 14 15] [16 17 18 19] [20 21 22 23]]
#### Level: Easy

In [11]:
a = np.array([[ 0,1,2,3],[ 4,5,6,7],[ 8,9,10,11]])
b = np.array([[12,13,14,15],[16,17,18,19],[20,21,22,23]])
print("a :",a,"\nb :",b)

a : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
b : [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [12]:
np.inner(a,b)

array([[ 86, 110, 134],
       [302, 390, 478],
       [518, 670, 822]])

### 5. Using given two array try to print out 3rd given array.
#### a = np.array(['a', 'b', 'c'], dtype=object) b = np.array([1,2,3])
#### output = [['a', 'aa', 'aaa'], ['b', 'bb', 'bbb'], ['c', 'cc', 'ccc']]
#### Level: Medium

In [15]:
a = np.array(['a', 'b', 'c'], dtype=object)
b = np.array([1,2,3])
print("a :",a,"\nb :",b)

a : ['a' 'b' 'c'] 
b : [1 2 3]


In [17]:
print("a :",a.shape,"\nb :",b.shape)

a : (3,) 
b : (3,)


In [20]:
a.reshape(3,1) * b

array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

### 6. Solve the system of equations 3 x0 + x1 = 9 and x0 + 2 x1 = 8
#### Level: Medium

In [21]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
np.linalg.solve(a,b)

array([2., 3.])

### 7. Check the following solution is right or wrong uisng numpy utilities.
#### 2x+3y=8 3x+y=5
#### solution: x=1 , y=2
#### Level : Medium

In [23]:
a = np.array([[2,3],[3,1]])
b = np.array([8,5])
res = np.linalg.solve(a,b)
res

array([1., 2.])

In [24]:
np.allclose(np.dot(a, res), b)

True

### 9. Write a program to add two arrays of different shape.
#### Hint: Broadcasting
#### Level: Medium
#### sample input:
#### a = [0.0,10.0,20.0,30.0]
#### b = [1.0,2.0,3.0]
#### output:
#### [[ 1., 2., 3.],
#### [ 11., 12., 13.],
#### [ 21., 22., 23.],
#### [ 31., 32., 33.]]

In [25]:
a = np.array([0.0,10.0,20.0,30.0])
b = np.array([1.0,2.0,3.0])
print("a :",a,"\nb :",b)

a : [ 0. 10. 20. 30.] 
b : [1. 2. 3.]


In [27]:
print("a :",a.shape,"\nb :",b.shape)

a : (4,) 
b : (3,)


In [30]:
a.reshape(4,1) + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

### 10. Create a 3 * 3 array find it's diagonal using numpy utilities.
#### Level: Hard

In [41]:
a = np.random.randint(1,10,(3,3))
a

array([[6, 8, 6],
       [1, 5, 7],
       [2, 9, 7]])

In [42]:
np.diag(a)

array([6, 5, 7])

### 11. Now find anti - diagonal in previous question using horizontal and vector flip.
#### Level: Hard

In [43]:
a

array([[6, 8, 6],
       [1, 5, 7],
       [2, 9, 7]])

In [46]:
np.fliplr(a).diagonal()

array([6, 5, 2])

In [47]:
np.flipud(a).diagonal()

array([2, 5, 6])

### 12. Create given array without using indexing.
#### a = [[4, 0, 0], [0, 4, 0], [0, 0, 4], [0, 0, 0], [4, 0, 0], [0, 4, 0], [0, 0, 4]]
#### Level : Hard

In [64]:
a = np.array([[4, 0, 0], [0, 4, 0], [0, 0, 4], [0, 0, 0], [4, 0, 0], [0, 4, 0], [0, 0, 4]])
print(a,a.shape)

[[4 0 0]
 [0 4 0]
 [0 0 4]
 [0 0 0]
 [4 0 0]
 [0 4 0]
 [0 0 4]] (7, 3)


In [84]:
new = (np.eye(7,3,k = -4) + np.eye(7,3,k = 0)) *4
new

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.],
       [0., 0., 0.],
       [4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])