### NumPy : Practice Problems 2: Solution
#### Easy Questions : 5
#### Moderate Questions : 7
#### Hard Questions : 3

In [1]:
import numpy as np

### 1. Create an array and find sum of it.
#### Level: Easy

In [2]:
a = np.array([1,5,2,4,6])
np.sum(a)

18

### 2. Find sin of given array.
#### Level: Easy

In [3]:
np.sin(a)

array([ 0.84147098, -0.95892427,  0.90929743, -0.7568025 , -0.2794155 ])

### 3. Find mean of matrix along row and column.
#### Level: Easy

In [4]:
matrix = np.random.randint(10,25,(3,3))
matrix

array([[11, 11, 19],
       [24, 10, 10],
       [20, 15, 16]])

In [5]:
np.mean(matrix , axis = 0) # mean by col

array([18.33333333, 12.        , 15.        ])

In [6]:
np.mean(matrix , axis = 1) # mean by row

array([13.66666667, 14.66666667, 17.        ])

### 4. Find standard deviation of given array.
#### Level: Easy

In [7]:
print(a)
np.std(a)

[1 5 2 4 6]


1.854723699099141

### 5. Create a 3*3 matrix and print it's transpose matrix
#### Level: Easy

In [8]:
mat = np.random.randint(10,25,(3,3))
mat

array([[19, 13, 12],
       [23, 19, 12],
       [11, 15, 19]])

In [9]:
mat.transpose()

array([[19, 23, 11],
       [13, 19, 15],
       [12, 12, 19]])

### 6. Create an array of 3*3 and find index of max along both axis.
#### Level: Medium

In [10]:
mat

array([[19, 13, 12],
       [23, 19, 12],
       [11, 15, 19]])

In [18]:
np.argmax(mat , axis =0)

array([1, 1, 2], dtype=int32)

In [20]:
np.argmax(mat , axis =1)

array([0, 0, 2], dtype=int32)

### 7. find sum of two matrix.
#### Level: Medium

In [13]:
mat

array([[19, 13, 12],
       [23, 19, 12],
       [11, 15, 19]])

In [14]:
mat.transpose()

array([[19, 23, 11],
       [13, 19, 15],
       [12, 12, 19]])

In [16]:
np.add(mat , mat.transpose())

array([[38, 36, 23],
       [36, 38, 27],
       [23, 27, 38]])

### 8. Find indexes of max element along axis=0 and axis=1 .
#### Level: Medium

In [21]:
matrix

array([[11, 11, 19],
       [24, 10, 10],
       [20, 15, 16]])

In [22]:
np.argmax(matrix , axis =0)

array([1, 2, 0], dtype=int32)

In [23]:
np.argmax(matrix , axis =1)

array([2, 0, 0], dtype=int32)

### 10. Try to solve a array and print a array with indices which would sort the given array.
#### sample input:
#### a = [3,1,8,2]
#### output:
#### [1,3,0,2]

In [25]:
a = [ 3, 1, 8, 2]
a = np.array(a)
np.argsort(a)

array([1, 3, 0, 2], dtype=int32)

### 11. Try to do perform same operation mentioned in previous questions for multidimentional array along both axis.
#### Level: Medium

In [26]:
mat

array([[19, 13, 12],
       [23, 19, 12],
       [11, 15, 19]])

In [29]:
print(np.sort(mat , axis = 0))  # sort along col
np.argsort(mat , axis = 0)

[[11 13 12]
 [19 15 12]
 [23 19 19]]


array([[2, 0, 0],
       [0, 2, 1],
       [1, 1, 2]], dtype=int32)

In [30]:
print(np.sort(mat , axis = 1))  # sort along row
np.argsort(mat , axis = 1)

[[12 13 19]
 [12 19 23]
 [11 15 19]]


array([[2, 1, 0],
       [2, 1, 0],
       [0, 1, 2]], dtype=int32)

### 12. calculate multiplication of transpose and matrix itself of a 3*3 matrix.
#### Level: Medium

In [31]:
matrix

array([[11, 11, 19],
       [24, 10, 10],
       [20, 15, 16]])

In [32]:
matrix.transpose()

array([[11, 24, 20],
       [11, 10, 15],
       [19, 10, 16]])

In [33]:
np.matmul( matrix , matrix.transpose() )

array([[603, 564, 689],
       [564, 776, 790],
       [689, 790, 881]])

### 13. Find solution for given linear equstion:
#### 2x + 5y = 28 4x + 3*y = 81
#### Level: Hard

In [37]:
a = np.array([[2 ,5],
             [4 ,3]])
b = np.array([28,81])
res = np.linalg.solve(a,b)
res

array([22.92857143, -3.57142857])

In [38]:
np.allclose(np.dot(a, res), b) # Checking the result

True

### 14. Find Rank, Trace, Inverse, Determinant of a given matrix.
#### A=[[1, 1, 1], [2, 2, 2], [3, 3, 3]])
#### Level: Hard

In [39]:
a = np.array([[1,1,1],[2,2,2],[3,3,3]])
a

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [41]:
np.linalg.matrix_rank(a)

1

In [42]:
np.trace(a)

6

In [52]:
a = np.matrix(a)
b = np.linalg.inv(a) #LinAlgError :If a is not square or inversion fails

LinAlgError: Singular matrix

In [53]:
np.linalg.det(a)

0.0

### 15. Find cube of a mtrix.
#### Level: Hard

In [54]:
mat

array([[19, 13, 12],
       [23, 19, 12],
       [11, 15, 19]])

In [55]:
np.linalg.matrix_power(mat, 3)

array([[37282, 32282, 29220],
       [46486, 40018, 36060],
       [38299, 33561, 30499]])