## NumPy : Practice Problems 1
#### Easy Questions : 7 Moderate Questions : 7 Hard Questions :3



### 1. Write a NumPy program to get the numpy version and show numpy build configuration.
#### Level: Easy

In [2]:
import numpy as np
print(np.version.version)
print(np.__config__)

1.16.1
<module 'numpy.__config__' from 'c:\\python37\\lib\\site-packages\\numpy\\__config__.py'>


### 2. Create a null vector of size 10 but the fifth value which is 1.
#### Level: Easy

In [2]:
ten_zeros = np.zeros(10)
ten_zeros[4] = 1
print(ten_zeros)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Create a vector with values ranging from 10 to 49.
#### Level: Easy

In [3]:
ten_fortynine = np.arange(10,50)
print(ten_fortynine)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 3. create two arrays and stack them vertically
#### Level: Easy

In [5]:
a , b = np.vsplit(np.random.randint(10,100,(5,4)),[3])
print("a =",a)
print("b =",b)

a = [[40 40 64 80]
 [52 97 43 88]
 [29 48 90 50]]
b = [[94 42 80 10]
 [58 13 20 49]]


In [9]:
res = np.vstack([b,a])
print(res)

[[94 42 80 10]
 [58 13 20 49]
 [40 40 64 80]
 [52 97 43 88]
 [29 48 90 50]]


### 4. Reverse a vector (first element becomes last).
#### Level: Easy

In [12]:
vector = np.arange(10,15)
print(vector)
print(vector[::-1])
print(np.flip(vector ,0))

[10 11 12 13 14]
[14 13 12 11 10]
[14 13 12 11 10]


### 5. Create a 3x3 matrix with values ranging from 0 to 8
#### Level: Easy

In [14]:
np.random.randint(0,8,(3,3))

array([[3, 1, 6],
       [0, 1, 6],
       [1, 6, 2]])

### 6. Find indices of non-zero elements from [1,2,0,0,4,0]
#### Level: Easy

In [22]:
arr = [1,2,0,0,4,0]
np.nonzero(arr)

(array([0, 1, 4], dtype=int32),)

### 7. Create a 10x10 array with random values and find the minimum and maximum values.
#### Level: Easy

In [17]:
data = np.random.randint(10,200,(10,10))
data

array([[ 37,  30,  11, 164,  74, 112, 136,  92, 167,  63],
       [176, 170, 185,  41, 138,  64, 188,  97,  95,  70],
       [182,  66,  43, 120,  20,  73, 103, 166,  99,  13],
       [ 83,  30,  50,  75,  68,  16,  28, 160,  64,  32],
       [195,  69, 126, 155, 144, 185,  70,  24,  85,  17],
       [ 58,  29,  37,  12,  31, 173, 171,  50, 110, 185],
       [105,  19, 106,  43, 183,  48, 111,  92, 142, 142],
       [ 67, 121,  95,  58, 174, 168,  65,  75, 132,  76],
       [189, 156,  98,  41, 118, 133, 176, 156,  15,  27],
       [107, 167,  60, 105,  53, 129,  78, 155, 105, 150]])

In [19]:
print(np.min(data))
print(np.max(data))

11
195


### 8. Create a random vector of size 30 and find the mean value.
#### Level: Medium

In [20]:
data = np.random.randint(10,100,(5,6))
data

array([[38, 74, 38, 17, 96, 65],
       [83, 92, 98, 80, 81, 74],
       [19, 49, 12, 81, 74, 26],
       [30, 73, 39, 95, 22, 25],
       [26, 55, 79, 90, 52, 50]])

In [21]:
np.mean(data)

57.766666666666666

### 9. Create a 2d array with 1 on the border and 0 inside
#### Level: Medium

In [23]:
oneborder = np.ones((10,10))
oneborder[1:-1,1:-1] = 0
print(oneborder)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 10. How to add a border (filled with 0's) around an existing array
#### Level: Medium

In [51]:
data = np.random.randint(10,30,(4,6))
data

array([[25, 24, 19, 18, 16, 18],
       [23, 18, 12, 11, 21, 28],
       [27, 29, 14, 24, 18, 29],
       [12, 28, 12, 24, 10, 16]])

In [53]:
data[:,0] = 0
data[:,-1] = 0
data[0] = 0
data[-1] =0
data

array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 18, 12, 11, 21,  0],
       [ 0, 29, 14, 24, 18,  0],
       [ 0,  0,  0,  0,  0,  0]])

##                               OR

In [52]:
data[:,[0,-1]] = 0
data[[0,-1] ,:] = 0
data

array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 18, 12, 11, 21,  0],
       [ 0, 29, 14, 24, 18,  0],
       [ 0,  0,  0,  0,  0,  0]])

### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
#### Sample Output:
##### [[ 0. 0. 0. 0. 0.] [ 1. 0. 0. 0. 0.] [ 0. 2. 0. 0. 0.] [ 0. 0. 3. 0. 0.] [ 0. 0. 0. 4. 0.]]
#### Level: Medium

In [54]:
data = np.zeros((5,5))
data

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
for i in range(5):
    data[i][i] = i
data

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 4.]])

## OR

In [64]:
np.diagflat([0,1,2,3,4])

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

### 12. Create a 5*5 matrix with random values and normalize it.
#### Level: Medium

In [67]:
data = np.random.randint(1,10,(5,5))
data

array([[8, 6, 7, 6, 3],
       [1, 4, 9, 2, 4],
       [3, 1, 6, 8, 1],
       [7, 3, 3, 2, 1],
       [7, 2, 7, 8, 6]])

In [68]:
xmax, xmin = data.max(), data.min()
data = (data - xmin)/(xmax - xmin)
data

array([[0.875, 0.625, 0.75 , 0.625, 0.25 ],
       [0.   , 0.375, 1.   , 0.125, 0.375],
       [0.25 , 0.   , 0.625, 0.875, 0.   ],
       [0.75 , 0.25 , 0.25 , 0.125, 0.   ],
       [0.75 , 0.125, 0.75 , 0.875, 0.625]])

### 13. How to find common values between two arrays
#### Level: Medium

In [79]:
a , b = np.vsplit(np.random.randint(10,100,(5,4)),[3])
print("a =",a)
print("b =",b)

a = [[71 74 31 93]
 [71 10 37 78]
 [40 77 36 20]]
b = [[24 20 94 88]
 [93 57 67 79]]


In [80]:
np.intersect1d(a,b)

array([20, 93])

### 14. Consider a generator function that generates 10 integers and use it to build an array
#### Level: Medium

In [5]:
def generator():
    for i in range(10):
        yield i
arr = np.fromiter(generator(),dtype=float)
print(arr)
print(type(arr))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>


### 15. Subtract the mean of each row of a matrix
#### Level: Hard

In [7]:
data = np.random.randint(10,50,(5,5))
data

array([[39, 20, 46, 15, 38],
       [16, 20, 42, 21, 18],
       [20, 16, 23, 24, 18],
       [40, 46, 18, 11, 16],
       [15, 38, 26, 24, 14]])

In [11]:
data.mean(axis = 1) # axis = 1 make sure that mean of individual row  & for individual col axis = 0

array([26. , 28. , 31. , 19. , 20.8])

In [9]:
res = data - data.mean(axis = 1)
res

array([[  7.4,  -3.4,  25.8, -11.2,  14.6],
       [-15.6,  -3.4,  21.8,  -5.2,  -5.4],
       [-11.6,  -7.4,   2.8,  -2.2,  -5.4],
       [  8.4,  22.6,  -2.2, -15.2,  -7.4],
       [-16.6,  14.6,   5.8,  -2.2,  -9.4]])

### 16. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
#### Level: Hard

In [21]:
a = np.random.randint(1,10,(1,3))
b = a.reshape(3,-1) 
print(a.shape ,b.shape)
print(a , b, sep='\n')

(1, 3) (3, 1)
[[4 6 9]]
[[4]
 [6]
 [9]]


In [ ]:
# incompelete

### 17. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
#### Level: Hard

In [6]:
def generator():
    for i in range(5,51):
        if i%5==0:
            yield i
arr = np.fromiter(generator(),dtype=float)
print(arr)
print(type(arr))

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
<class 'numpy.ndarray'>
