## NumPy Graded Test 1

In [1]:
import numpy as np

### 1. Count The Number Of Times Each Value Appears In An Array Of Integers

In [11]:
a = np.array([1,2,4,2,4,1,3,5])
unique_ele , counts = np.unique(a , return_counts = True)
print(unique_ele , counts , sep = '\n')

[1 2 3 4 5]
[2 2 1 2 1]


### 2. Given 9 Integers. You have to convert them into 3*3 Numpy array using Reshape function.

In [12]:
a = np.array([1,3,5,2,4,6,7,8,9])
a.reshape(3,3)

array([[1, 3, 5],
       [2, 4, 6],
       [7, 8, 9]])

### 3. How to find the memory size of any array

In [18]:
a = np.array([1,3,5,2,4,6,7,8,9])
print('Size of array : ',a.size ,'Size of each element :', a.itemsize ,'Total memory size of array :', a.nbytes , sep ='\n')


Size of array : 
9
Size of each element :
4
Total memory size of array :
36


### 4. Create a 2d array of size 10 by 10 with 1 on the border and 0 inside.

In [45]:
a = np.zeros((10,10))
a[:,[0,-1]] = 1
a[[0,-1],:] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### OR

In [46]:
oneborder = np.ones((10,10))
oneborder[1:-1,1:-1] = 0
print(oneborder)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 5.Create a 8x8 matrix and fill it with a checkerboard pattern.

In [72]:
checkerboard = np.eye(8)
for i in range(1 ,checkerboard.shape[0]):
    if i % 2 == 0:
        checkerboard += np.eye(checkerboard.shape[0],k = i) + np.eye(checkerboard.shape[0],k = -i)
print(checkerboard)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


### 6. Normalize a 5x5 random matrix.

In [75]:
matrix = np.random.randint(1,10,(5,5))
matrix

array([[2, 6, 2, 2, 5],
       [7, 7, 7, 2, 5],
       [6, 7, 7, 4, 9],
       [7, 9, 1, 4, 5],
       [3, 1, 4, 3, 4]])

In [77]:
Normalized_Matrix = (matrix - np.mean(matrix)) / matrix.std()
Normalized_Matrix

array([[-1.18091145,  0.53055442, -1.18091145, -1.18091145,  0.10268795],
       [ 0.95842088,  0.95842088,  0.95842088, -1.18091145,  0.10268795],
       [ 0.53055442,  0.95842088,  0.95842088, -0.32517851,  1.81415382],
       [ 0.95842088,  1.81415382, -1.60877791, -0.32517851,  0.10268795],
       [-0.75304498, -1.60877791, -0.32517851, -0.75304498, -0.32517851]])

### 7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place.

In [78]:
data = np.arange(0,11)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
np.place(data , (data > 3) & (data < 8) ,-data[np.where( (data > 3) & (data < 8))] )
data

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

### 8. How to get the dates of yesterday, today and tomorrow?

In [98]:
yesterday = np.datetime64('today' ,'D') - np.timedelta64(1 ,'D')
today = np.datetime64('today' ,'D')
tomorrow = np.datetime64('today' ,'D') + np.timedelta64(1 ,'D')
print(yesterday , today , tomorrow ,sep='\n')

2020-02-13
2020-02-14
2020-02-15


### 9. Generate two arrays of size 2X4 & 3X3, find difference between them.

In [99]:
a = np.random.randint(1,10,(2,4))
b = np.random.randint(1,10,(3,3))
print("a :",a,"\nb :",b)

a : [[9 3 1 4]
 [1 2 3 3]] 
b : [[9 9 8]
 [3 9 4]
 [5 2 1]]


In [105]:
a.reshape(2,1,4) - b.reshape(3,1,3)

ValueError: operands could not be broadcast together with shapes (2,1,4) (3,1,3) 

### 10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?
#### ['cat','cat',...,'rat','dog','dog','cat'...]

In [108]:
x = np.random.choice(['cat','dog','rat'] , 100)

In [109]:
x.shape

(100,)

In [110]:
x

array(['cat', 'cat', 'cat', 'cat', 'dog', 'dog', 'rat', 'cat', 'rat',
       'cat', 'rat', 'cat', 'cat', 'rat', 'rat', 'rat', 'cat', 'dog',
       'cat', 'rat', 'dog', 'rat', 'cat', 'dog', 'cat', 'cat', 'dog',
       'dog', 'rat', 'dog', 'dog', 'cat', 'cat', 'cat', 'cat', 'cat',
       'rat', 'dog', 'dog', 'dog', 'cat', 'dog', 'dog', 'dog', 'dog',
       'rat', 'dog', 'dog', 'dog', 'dog', 'rat', 'rat', 'cat', 'rat',
       'dog', 'rat', 'rat', 'rat', 'cat', 'cat', 'cat', 'cat', 'cat',
       'dog', 'rat', 'dog', 'rat', 'rat', 'rat', 'dog', 'rat', 'rat',
       'cat', 'rat', 'rat', 'rat', 'rat', 'cat', 'cat', 'rat', 'cat',
       'dog', 'cat', 'dog', 'rat', 'rat', 'cat', 'rat', 'rat', 'rat',
       'rat', 'cat', 'cat', 'cat', 'dog', 'dog', 'dog', 'dog', 'dog',
       'rat'], dtype='<U3')

### 11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values

In [112]:
n = np.random.rand(10)
n

array([0.86756669, 0.26333297, 0.43410837, 0.63926815, 0.53701595,
       0.27257943, 0.0030317 , 0.52602008, 0.41450663, 0.93502098])

### 12. Given a two dimensional array, how to extract unique rows?

In [118]:
a = np.random.randint(1,10,(3,3))
print(a)
np.unique(a , axis = 0)

[[1 1 7]
 [8 7 9]
 [5 7 6]]


array([[1, 1, 7],
       [5, 7, 6],
       [8, 7, 9]])

### 13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

In [119]:
np.array([0,1]) * np.array([1,0])

array([0, 0])

### 14. How to find the closest value (to a given scalar) in a vector?

In [128]:
a = np.random.randint(10,100,(10,))
a

array([40, 82, 58, 67, 40, 35, 22, 30, 75, 40])

In [129]:
a[(np.abs(a-11)).argmin()]

22

### 15. Consider a random vector with shape (10,2) representing coordinates, find point by point distances. Use euclidian distance.

In [131]:
a = np.random.randint(10,100,(10,2))
a

array([[98, 10],
       [94, 51],
       [19, 30],
       [25, 40],
       [46, 89],
       [71, 16],
       [76, 96],
       [86, 79],
       [65, 42],
       [26, 70]])

In [134]:
a.reshape(1,10,2) - a.reshape(2,10,1)

array([[[  0, -88],
        [ 84,  41],
        [-75, -64],
        [-26, -11],
        [ 27,  70],
        [ 41, -14],
        [ 51,  71],
        [ 46,  39],
        [ 19,  -4],
        [-63, -19]],

       [[ 27, -61],
        [ 78,  35],
        [-57, -46],
        [-71, -56],
        [-40,   3],
        [ -8, -63],
        [ 11,  31],
        [ 44,  37],
        [ 39,  16],
        [-44,   0]]])

### 16. How to sort an array by the nth column?

### 17.How to tell if a given 2D array has null columns?

In [139]:
a = np.random.randint(0,2,(5,5))
a

array([[1, 0, 0, 1, 1],
       [1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 1, 0, 0]])

In [141]:
~a.any(axis=0)

array([False, False, False, False, False])

In [140]:
(~a.any(axis=0)).any()

False

### 19. Given a 2d array of 5X5, increment 1st column by 1, second column by 2, 3rd column by 3 & so on till the last column

In [151]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [150]:
for i in range(a.shape[1]):
    a[:,i] += i
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### 20. Given a 1d array(size 100) of boolean values, identify total number of True in it.

In [153]:
x = np.random.choice(['True','False'] , 100)
x

array(['False', 'False', 'False', 'True', 'True', 'False', 'False',
       'True', 'False', 'False', 'True', 'False', 'True', 'True', 'False',
       'True', 'True', 'False', 'True', 'False', 'False', 'False',
       'False', 'False', 'True', 'False', 'False', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'False', 'False', 'False',
       'True', 'True', 'False', 'False', 'False', 'False', 'True',
       'False', 'True', 'True', 'False', 'True', 'True', 'True', 'True',
       'False', 'True', 'True', 'True', 'False', 'False', 'False',
       'False', 'True', 'False', 'False', 'True', 'False', 'True', 'True',
       'True', 'True', 'True', 'False', 'True', 'False', 'False', 'False',
       'True', 'False', 'False', 'False', 'True', 'False', 'False',
       'True', 'True', 'False', 'False', 'True', 'False', 'True', 'False',
       'False', 'True', 'True', 'False', 'False', 'False', 'True',
       'False', 'False'], dtype='<U5')

In [164]:
trues = x[np.where(x == 'True')]
trues

array(['True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True'],
      dtype='<U5')

In [165]:
trues.size

47

### 21. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [166]:
a = np.array( [1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [175]:
new = np.array([])
for i in a:
    new = np.append(new ,[i,0,0,0])
print(new)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


### 22. How to swap two rows of an array?

In [182]:
a = np.random.randint(0,10,(4,4))
a

array([[6, 6, 7, 4],
       [7, 5, 3, 9],
       [9, 3, 2, 0],
       [0, 8, 0, 9]])

In [183]:
a[[1,2],:] = a[[2,1],:]
a

array([[6, 6, 7, 4],
       [9, 3, 2, 0],
       [7, 5, 3, 9],
       [0, 8, 0, 9]])

### 24. How to get n largest value of an array?

In [184]:
a = np.random.randint(1,100,(50))
a

array([43, 89, 46, 65, 71, 77, 54, 99,  8, 71, 21, 33, 67, 70, 73, 63,  9,
       96, 85,  3, 86, 85, 63, 38, 20, 31, 92, 36, 27, 55, 98, 85, 24, 59,
       72, 33,  4, 34, 96, 38, 88, 94, 93, 23, 91, 79, 38, 46, 10, 67])

In [194]:
a = np.sort(a)
a

array([ 3,  4,  8,  9, 10, 20, 21, 23, 24, 27, 31, 33, 33, 34, 36, 38, 38,
       38, 43, 46, 46, 54, 55, 59, 63, 63, 65, 67, 67, 70, 71, 71, 72, 73,
       77, 79, 85, 85, 85, 86, 88, 89, 91, 92, 93, 94, 96, 96, 98, 99])

In [193]:
a[-int(input()):]

8


array([91, 92, 93, 94, 96, 96, 98, 99])

### 25. Given two random arrays of shape 5X5, identify the common elements between them.

In [195]:
a = np.random.randint(10,50,(5,5))
b = np.random.randint(10,50,(5,5))
print("a :",a,"\nb :",b)

a : [[37 29 21 22 13]
 [14 20 35 34 27]
 [39 21 40 11 13]
 [26 47 43 11 18]
 [22 12 13 26 12]] 
b : [[30 31 43 25 11]
 [10 29 49 28 11]
 [35 30 32 39 45]
 [27 12 44 36 29]
 [37 24 14 38 48]]


In [196]:
np.intersect1d(a,b)

array([11, 12, 14, 27, 29, 35, 37, 39, 43])

### 26. How to get index of top two highest value in a 1d array?

In [202]:
a = np.array([2,22,11,-11,33,7,13,872,-23])
a

array([  2,  22,  11, -11,  33,   7,  13, 872, -23])

In [203]:
np.sort(a)

array([-23, -11,   2,   7,  11,  13,  22,  33, 872])

In [206]:
np.argsort(a)

array([8, 3, 0, 5, 2, 6, 1, 4, 7], dtype=int32)

In [207]:
np.argsort(a)[-2:]

array([4, 7], dtype=int32)