# **Use all the other ratings to create a model to predict if somebody will take gym membership or now.**

In [0]:
import pandas as pd
import numpy as np

In [1]:
from google.colab import files
uploaded = files.upload()

Saving google_review_ratings.csv to google_review_ratings.csv


In [10]:
data = pd.read_csv('google_review_ratings.csv', index_col='User')
data

Category 1  Category 2  ...  Category 24  Unnamed: 25
User                               ...                          
User 1           0.00        0.00  ...         0.00          NaN
User 2           0.00        0.00  ...         0.00          NaN
User 3           0.00        0.00  ...         0.00          NaN
User 4           0.00        0.50  ...         0.00          NaN
User 5           0.00        0.00  ...         0.00          NaN
...               ...         ...  ...          ...          ...
User 5452        0.91        5.00  ...         1.56          NaN
User 5453        0.93        5.00  ...         1.09          NaN
User 5454        0.94        5.00  ...         1.11          NaN
User 5455        0.95        4.05  ...         1.12          NaN
User 5456        0.95        4.07  ...         1.17          NaN

[5456 rows x 25 columns]

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5456 entries, User 1 to User 5456
Data columns (total 25 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Category 1   5456 non-null   float64
 1   Category 2   5456 non-null   float64
 2   Category 3   5456 non-null   float64
 3   Category 4   5456 non-null   float64
 4   Category 5   5456 non-null   float64
 5   Category 6   5456 non-null   float64
 6   Category 7   5456 non-null   float64
 7   Category 8   5456 non-null   float64
 8   Category 9   5456 non-null   float64
 9   Category 10  5456 non-null   float64
 10  Category 11  5456 non-null   object 
 11  Category 12  5455 non-null   float64
 12  Category 13  5456 non-null   float64
 13  Category 14  5456 non-null   float64
 14  Category 15  5456 non-null   float64
 15  Category 16  5456 non-null   float64
 16  Category 17  5456 non-null   float64
 17  Category 18  5456 non-null   float64
 18  Category 19  5456 non-null   float64
 19  C

In [0]:
# converting the col Category 11 from object to float type
data['Category 11'] = data['Category 11'].astype(float)

In [0]:
data = data[data['Unnamed: 25'].isnull()]
data.drop(columns=['Unnamed: 25'], inplace=True)

In [16]:
data

Category 1  Category 2  ...  Category 23  Category 24
User                               ...                          
User 1           0.00        0.00  ...          0.0         0.00
User 2           0.00        0.00  ...          0.0         0.00
User 3           0.00        0.00  ...          0.0         0.00
User 4           0.00        0.50  ...          0.0         0.00
User 5           0.00        0.00  ...          0.0         0.00
...               ...         ...  ...          ...          ...
User 5452        0.91        5.00  ...          5.0         1.56
User 5453        0.93        5.00  ...          5.0         1.09
User 5454        0.94        5.00  ...          5.0         1.11
User 5455        0.95        4.05  ...          5.0         1.12
User 5456        0.95        4.07  ...          5.0         1.17

[5454 rows x 24 columns]

In [37]:
data.describe()

Category 1   Category 2  ...  Category 23  Category 24
count  5454.000000  5454.000000  ...  5454.000000  5454.000000
mean      1.455746     2.320048  ...     1.531051     1.560570
std       0.827732     1.421576  ...     1.316180     1.171784
min       0.000000     0.000000  ...     0.000000     0.000000
25%       0.920000     1.360000  ...     0.790000     0.880000
50%       1.340000     1.910000  ...     1.070000     1.290000
75%       1.810000     2.687500  ...     1.560000     1.660000
max       5.000000     5.000000  ...     5.000000     5.000000

[8 rows x 24 columns]

**Here we don't have a target column. we create one by taking avg rating of cols in a row.**
* if avg <= 2 : 0 will not take membership
* elif avg > 2: 1 will take membership

In [0]:
def f(r):
  a = round(np.average(np.array(r.values)))
  if a <= 2:
    return 0
  else :
    return 1


data['take_membership'] = data.apply(f, axis=1)

In [44]:
data.take_membership.value_counts()

1    2858
0    2596
Name: take_membership, dtype: int64

In [49]:
data.sample(5)

Category 1  Category 2  ...  Category 24  take_membership
User                               ...                              
User 3819        1.40        1.41  ...         1.40                1
User 2038        1.42        1.67  ...         1.40                0
User 4557        0.98        1.02  ...         0.97                0
User 222         1.39        1.39  ...         1.42                0
User 846         2.65        2.63  ...         5.00                0

[5 rows x 25 columns]

# **Spliting Data**

In [0]:
feature_data = data.drop(columns=['take_membership'])
target_data = data.take_membership

In [0]:
from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split(feature_data, target_data)

# **RandomForest Classifier**

In [0]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

In [54]:
from sklearn.pipeline import make_pipeline
pipeline = make_pipeline(StandardScaler(), RandomForestClassifier())
pipeline.fit(trainX, trainY)

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('randomforestclassifier',
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=100, n_jobs=None,
                                        oob_score=False, random_state=None,
                                        verbose=0, warm_start=False))],
         verbose=F

In [55]:
pipeline.score(testX,testY)

0.8922287390029325

In [0]:
y_pred = pipeline.predict(testX)

In [57]:
from sklearn.metrics import confusion_matrix
confusion_matrix(testY, y_pred)

array([[602,  74],
       [ 73, 615]])

<hr>

# **Applying feature Selection**

In [0]:
from sklearn.feature_selection import SelectKBest, f_classif

In [0]:
pipeline = make_pipeline(StandardScaler(), SelectKBest(k=10, score_func=f_classif), RandomForestClassifier(n_estimators=100))

In [61]:
pipeline.fit(trainX, trainY)

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('selectkbest',
                 SelectKBest(k=10,
                             score_func=<function f_classif at 0x7f33b16e3e18>)),
                ('randomforestclassifier',
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=100, n_jobs=None,
                 

In [62]:
pipeline.score(testX,testY)

0.8717008797653959

<hr>

# **Hyper-parameter tuning GridSearchCV**

In [0]:
from sklearn.model_selection import GridSearchCV

In [0]:
params = {'selectkbest__k':[15,20,24], 'randomforestclassifier__n_estimators':[100,200,250]}

In [0]:
gs = GridSearchCV(pipeline, param_grid=params, cv=5, n_jobs=4)

In [66]:
gs.fit(trainX, trainY)

GridSearchCV(cv=5, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('standardscaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('selectkbest',
                                        SelectKBest(k=10,
                                                    score_func=<function f_classif at 0x7f33b16e3e18>)),
                                       ('randomforestclassifier',
                                        RandomForestClassifier(bootstrap=True,
                                                               ccp_alpha=0.0,
                                                               class_weight=None,
                                                               criterion='gini',
                                                

In [67]:
gs.best_params_

{'randomforestclassifier__n_estimators': 200, 'selectkbest__k': 24}

In [68]:
gs.best_score_

0.8975550122249387

<hr>

# **Logistic Regression**

In [69]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(trainX,trainY)
lr.score(testX,testY)

0.9934017595307918

In [70]:
y_pred = lr.predict(testX)
y_pred

array([0, 0, 1, ..., 1, 0, 1])

In [71]:
confusion_matrix(testY, y_pred)

array([[669,   7],
       [  2, 686]])

# **Conclusion :**
* Some times the simple models give the best accuracy.

  **What is learned ?**
  * start impelementing the simple models first.
